site_name: bartsmeding.nl | network/infra automation | tutorials | blog | courses
site_author: Bart Smeding
site_url: https://bsmeding.github.io/
repo_name: bsmeding/bsmeding.github.io

plugins:
  - blog:
      blog_dir: blog
      post_url_format: "{slug}"
      blog_toc: true
      categories_toc: false
      archive_name: "Blogs"
      pagination_per_page: 4
  - search:
      lang: en
  - tags:
      tags_file: tags.md
nav:
  - Home: index.md
  - About: about.md
  - Blog:
    - blog/index.md  
  - Tutorials:
    - 'Tutorials': tutorials.md
    - 'Tutorials 2': tutorials2.md
  - Courses:
    - 'Courses': courses.md
    - 'Courses 2': courses2.md
  - Contact: contact.md
theme:
  name: material
  palette:
    primary: blue
    accent: light blue
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  feature:
    tabs: true
    highlightjs: true
    mermaid: true
    mathjax: true
  features:
    - navigation.sections
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - content.code.copy
    - content.action.view
    - content.tabs.link
    - search.share
    - search.suggest
  search:
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/bsmeding
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/bartsmeding/
    # - icon: fontawesome/brands/twitter
    #   link: https://twitter.com/bsmeding
