site_name: NetDevOps.it
site_description: "Network & Infra Automation – Tutorials • Blog • Courses"
site_url: https://netdevops.it/
site_author: Bart Smeding
repo_url: https://github.com/bsmeding/bsmeding.github.io
edit_uri: edit/main/docs/

plugins:
  - blog:
      post_url_format: "{slug}"
      blog_toc: true
      pagination_per_page: 4
  - tags:
      tags_file: tags.md
  - search:
      lang: en
  - git-revision-date-localized
  - rss:
      match_path: blog/posts/.*
      date_from_meta:
        as_creation: date

nav:
  - Home: index.md
  - Ansible:
    - 'Ansible Roles & Collections': ansible_roles_and_collections.md
    - 'bsmeding.docker': ansible/ansible_role_docker.md
    - 'bsmeding.nautobot_docker': ansible/ansible_role_nautobot_docker.md
    - 'bsmeding.awx_docker': ansible/ansible_role_awx_docker.md
    - 'bsmeding.nginx_docker': ansible/ansible_role_nginx_docker.md
    - 'bsmeding.gitlab_ce_docker': ansible/ansible_role_gitlab_docker.md
    - 'bsmeding.swag_docker': ansible/ansible_role_swag_docker.md
  - Nautobot:
    - 'Nautobot SSoT': nautobot_ssot.md
    - 'Nautobot Docker Apps': blog/posts/2025/2025-04-10-nautobot-docker-apps.md
    # - 'Nautobot Jobs': nautobot_jobs.md
    # - 'Nautobot Plugins': nautobot_plugins.md
  - Docker:
    - 'Docker images index': docker_images.md
  - AI:
    - 'AI in networking': ai/ai_in_networking.md
  - Blog:
    - blog/index.md  
  - Tutorials:
    - 'Tutorials Overview': tutorials.md
    - 'Ansible Tutorial 1: Concepts & Terminology': tutorials/ansible_tutorial_1_concepts.md
    - 'Ansible Tutorial 2: Modules & Your First Playbook': tutorials/ansible_tutorial_2_modules.md
    - 'Ansible Tutorial 3: Variables, Modules & Network Fact Gathering': tutorials/ansible_tutorial_3_variables_facts.md
    - 'Ansible NAPALM': tutorials/ansible_cisco_napalm_diff.md
    - 'Git basics': tutorials/git_basics.md
    - 'Linux basics': tutorials/linux_basics.md
    - 'Enable Windows Subsystem for Linux': tutorials/enable_wsl_on_windows.md
    - 'Vagrant Installation': tutorials/vagrant_install.md
    - 'SSO: Introduction': sso.md
  - Tools:
    - 'Tools Index': tools.md
    - 'Ansible': blog/posts/tools/ansible.md
    - 'Docker': blog/posts/tools/docker.md
    - 'NetBox': blog/posts/tools/netbox.md
    - 'Nautobot': blog/posts/tools/nautobot.md
    - 'OpsMill': blog/posts/tools/opsmill.md
    - 'Jinja2': blog/posts/tools/jinja2.md
    - 'Nornir': blog/posts/tools/nornir.md
    - 'Terraform': blog/posts/tools/terraform.md
    - 'SaltStack': blog/posts/tools/saltstack.md
    - 'pyATS': blog/posts/tools/pyats.md
    - 'Prometheus': blog/posts/tools/prometheus.md
    - 'Grafana': blog/posts/tools/grafana.md
    - 'InfluxDB': blog/posts/tools/influxdb.md
    - 'Jenkins': blog/posts/tools/jenkins.md
    - 'GitLab CI/CD': blog/posts/tools/gitlab-ci.md
    - 'GitHub Actions': blog/posts/tools/github-actions.md
    - 'CloudFormation': blog/posts/tools/cloudformation.md
    - 'API': blog/posts/tools/api.md
  - Web Tools:
    - 'Web Tools Overview': online-dev-tools/index.md
    - 'YAML Validator': online-dev-tools/yaml-validator.md
    - 'Regex Tester': online-dev-tools/regex-tester.md
    - 'JSON Validator': online-dev-tools/json-validator.md
    - 'Diff Tool': online-dev-tools/diff-tool.md
    - 'Base64 Converter': online-dev-tools/base64-converter.md
    - 'URL Encoder/Decoder': online-dev-tools/url-encoder.md
    - 'Hash Generator': online-dev-tools/hash-generator.md
    - 'Color Converter': online-dev-tools/color-converter.md
  - Courses:
    - 'Courses': courses.md
    - 'Courses Dutch': courses_NL.md
  - About: about-bart-smeding.md
  - Privacy Policy: privacy.md

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch theme
    - scheme: default
      primary: indigo
      accent: blue
    - scheme: slate
      primary: indigo
      accent: blue
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.sections
    - navigation.indexes
    - navigation.prune
    - content.code.copy
    - content.tabs.link
    - search.share
    - search.suggest

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
  - pymdownx.inlinehilite
  - pymdownx.superfences

## EXTRA
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/bartsmeding/
  analytics:
    provider: google
    property: G-LF84C44PGC

extra_javascript:
  - js/giscus.js
  - https://cdn.jsdelivr.net/npm/cookieconsent@3/build/cookieconsent.min.js
  - js/cookieconsent-init.js

extra_css:
  - https://cdn.jsdelivr.net/npm/cookieconsent@3/build/cookieconsent.min.css
  - css/full-width.css

