site_name: NetDevOps.it
site_description: "Network & Infra Automation – Tutorials • Blog • Courses"
site_url: https://netdevops.it/
site_author: Bart Smeding
repo_url: https://github.com/bsmeding/bsmeding.github.io
edit_uri: edit/main/docs/

plugins:
  - blog:
      post_url_format: "{slug}"
      blog_toc: true
      pagination_per_page: 4
  - tags:
      tags_file: tags.md
  - search:
      lang: en
  - git-revision-date-localized
  - rss:
      match_path: blog/posts/.*
      date_from_meta:
        as_creation: date

nav:
  - Home: index.md
  - NetDevOps: netdevops.md
  - Ansible:
    - 'ansible role and collection index': ansible_roles_and_collections.md
    - 'role: Docker': ansible/ansible_role_docker.md
    - 'bsmeding.docker': ansible/ansible_role_docker.md
    - 'bsmeding.nginx_docker': ansible/ansible_role_nginx_docker.md
    - 'bsmeding.gitlab_docker': ansible/ansible_role_gitlab_docker.md
  - Docker:
    - 'Docker images index': docker_images.md
  - AI:
    - 'AI in networking': ai_in_networking.md
  - Blog:
    - blog/index.md  
  - Tutorials:
    - 'Tutorials': tutorials.md
    - 'Ansible NAPALM': tutorials/ansible_cisco_napalm_diff.md
    - 'Git basics': tutorials/git_basics.md
    - 'Linux basics': tutorials/linux_basics.md
    - 'Enable Winwows Subsystem for Linux': tutorials/enable_wsl_on_windows.md
  - Courses:
    - 'Courses': courses.md
    - 'Courses Dutch': courses_NL.md
  - About: about.md
  - Contact: contact.md

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch theme
    - scheme: default
      primary: indigo
      accent: blue
    - scheme: slate
      primary: indigo
      accent: blue
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.sections
    - navigation.indexes
    - content.code.copy
    - content.tabs.link
    - search.share
    - search.suggest
  privacy:
    analytics:
      google: G-LF84C44PGC
      cookie: true

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/bartsmeding/

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
  - pymdownx.inlinehilite
  - pymdownx.superfences