site_name: netdevops.it | bartsmeding.nl | network/infra automation | tutorials | blog | courses
site_author: Bart Smeding
site_url: https://netdevops.it/
repo_name: bsmeding/bsmeding.github.io

plugins:
  - blog:
      # blog_dir: blog
      post_url_format: "{slug}"
      blog_toc: true
      categories_toc: false
      # archive_name: "Blogs"
      pagination_per_page: 4
  # - rss:
  #     match_path: blog/posts/.* 
  #     date_from_meta:
  #       as_creation: date
  #     categories:
  #       - categories
  #       - tags 
  - search:
      lang: en
  - tags:
      tags_file: tags.md
nav:
  - Home: index.md
  - About: about.md
  - Blog:
    - blog/index.md  
  - Tutorials:
    - 'Tutorials': tutorials.md
    - 'Ansible NAPALM': tutorials/ansible_cisco_napalm_diff.md
  - Courses:
    - 'Courses': courses.md
    - 'Courses Dutch': courses_NL.md
  - Contact: contact.md
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: gray
      accent: blue
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode    
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  feature:
    tabs: true
    highlightjs: true
    mermaid: true
    mathjax: true
  features:
    - navigation.sections
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - content.code.copy
    - content.action.view
    - content.tabs.link
    - search.share
    - search.suggest
  search:
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/bsmeding
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/bartsmeding/
    # - icon: fontawesome/brands/twitter
    #   link: https://twitter.com/bsmeding
